<?php

use Illuminate\Database\Seeder;
use App\Models\Frs\Counterpart;
class CounterpartsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Counterpart::truncate();
        Counterpart::create(['name'=>'Abel da Conceição','gender'=>'M','municipal_id'=>'1','position_id'=>'1','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Armindo Martins Vilar Moreira','gender'=>'M','municipal_id'=>'1','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Artur Egas Martins Freitas','gender'=>'M','municipal_id'=>'1','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Celso Julio Babo','gender'=>'M','municipal_id'=>'1','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Reinaldo da Costa Silva Bacun','gender'=>'M','municipal_id'=>'1','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gil da Costa Cristovão','gender'=>'M','municipal_id'=>'1','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Constancia Fatima Lahalelo','gender'=>'F','municipal_id'=>'1','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gilberto Mendonca Menezes','gender'=>'M','municipal_id'=>'1','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julieta de Deus','gender'=>'F','municipal_id'=>'1','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Pedro Mendes','gender'=>'M','municipal_id'=>'1','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Renato Amaral da Cruz','gender'=>'M','municipal_id'=>'1','position_id'=>'5','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Assis de Jesus','gender'=>'M','municipal_id'=>'1','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elias Soares','gender'=>'M','municipal_id'=>'1','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fatima Nunes','gender'=>'F','municipal_id'=>'1','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mouzinho Santiago','gender'=>'M','municipal_id'=>'1','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Pedro Cachola','gender'=>'M','municipal_id'=>'1','position_id'=>'6','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Abrao Nacimento da Costa','gender'=>'M','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos de Jesus','gender'=>'M','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos Lotero','gender'=>'M','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlota Abrantes Araujo','gender'=>'F','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Daniel Frederico','gender'=>'M','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Luciana Ximenes','gender'=>'F','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marçal da Silva','gender'=>'M','municipal_id'=>'1','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zaido da Costa Pereira','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Filomeno Seixas Pinto','gender'=>'M','municipal_id'=>'2','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Virginia de Araujo','gender'=>'F','municipal_id'=>'2','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'João Paulo de Braz Carvalho e Corte','gender'=>'M','municipal_id'=>'2','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Newsa Belo Magno','gender'=>'F','municipal_id'=>'2','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aryanto de Orlaens Amaro','gender'=>'M','municipal_id'=>'2','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Floriana da Silva Barros','gender'=>'F','municipal_id'=>'2','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Graziela Ines Amaral de Almeida','gender'=>'F','municipal_id'=>'2','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Humberto Doutel Sarmento','gender'=>'M','municipal_id'=>'2','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Tiago Mendonca Babo','gender'=>'M','municipal_id'=>'2','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agostinho Doutel Sarmento','gender'=>'M','municipal_id'=>'2','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rogerio da Costa','gender'=>'M','municipal_id'=>'2','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rogerio de Jesus Martins','gender'=>'M','municipal_id'=>'2','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Venerando Gonçalves','gender'=>'M','municipal_id'=>'2','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio Mendonça Tilman','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Domingos Alves Quintão','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jonato Dias de Araujo Xavier','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jonio Jose Bossa','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Juliao Borges Magno','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Santiago Ximenes Marques','gender'=>'M','municipal_id'=>'2','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Valdemiro de Araujo Magalhães','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lino Furtuoso Moreira Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Amelia Maria Viegas','gender'=>'F','municipal_id'=>'3','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Celestino Moreira','gender'=>'M','municipal_id'=>'3','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eugenia Cardoso','gender'=>'F','municipal_id'=>'3','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Germano Freitas Moreira','gender'=>'M','municipal_id'=>'3','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Olimpio da Silva Gomes','gender'=>'M','municipal_id'=>'3','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agostinha Jeronimo','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elisa Francisca Pereira','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Irene Adelina Freitas','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Madalena do Rosario Castro','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marciana Baptista da Silva','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria de Lourdes dos Santos','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Evelina de Fatima Guterres','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Meliana Fatima dos Reis Costa','gender'=>'F','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zulmiro Aniceto Gusmão','gender'=>'M','municipal_id'=>'3','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Adelino da Silva','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Afonso Graciano Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Amaro Gusmão Gama Fernandes','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Helder de Orleans Soares','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jacinta Alves Pereira','gender'=>'F','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria de Fatima Belo','gender'=>'F','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mateus Pinto Guterres','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rui Fernando da Conceição','gender'=>'M','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Tertuliana da Silva','gender'=>'F','municipal_id'=>'3','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Afonso Belo Freitas Ximenes','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ananias Valentim','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos da Costa Ximenes','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Cidalio da Costa Guterres Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernanda Ximenes','gender'=>'F','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Guido José Lemos da Silva','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Honorio Valdemar Belo','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Hugo Juno Mario Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joao  Sarmento Piedade','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio da Costa Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Juvenal Daniel Filipe Belo','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Norberta Maria Guterres','gender'=>'F','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Nuno Alves Pinto','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Samuel Ximenes','gender'=>'M','municipal_id'=>'3','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zacarias da Silva','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Paulino Viegas Tilman','gender'=>'M','municipal_id'=>'4','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elizeu Lopes de Araujo','gender'=>'M','municipal_id'=>'4','position_id'=>'2','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Maria de Fatima','gender'=>'F','municipal_id'=>'4','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alfredo da Silva Tilman','gender'=>'M','municipal_id'=>'4','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Martins','gender'=>'M','municipal_id'=>'4','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Franzinho Margues','gender'=>'M','municipal_id'=>'4','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Angela de Fatima de Cunha','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Avelina Gomes','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Azelia Luisa','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eugenio Leonetu Guterres','gender'=>'M','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernanda Moniz Noronha','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joaninha de Oliveira Marcal','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lidia de Fatima  Godinho','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marciana Ximenes de Oliveira','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Veronica Maia Cairo','gender'=>'F','municipal_id'=>'4','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonino Barreto Amaral','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Belina da Silva Manuel Leite','gender'=>'F','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos Araujo dos Santos','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Crisanto de Araujo Boki','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Florindo da Silva Miguel','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mateus Barros Gonçalves','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zeca Michael Lopes','gender'=>'M','municipal_id'=>'4','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Abel Aip Tukan','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Almeida Soares','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Frederico Talo Bere Claudino','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gaspar Pimentel','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Januario Henriques Maia','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jeremias Costa dos Santos','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lidia Martins de Araujo','gender'=>'F','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Esteves','gender'=>'F','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Octavio Ribeiro Gama','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ozorio de Souza','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ramalia Guterres Borges','gender'=>'F','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosario Mali dos Santos','gender'=>'M','municipal_id'=>'4','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Filipe Cardoso Vieira','gender'=>'M','municipal_id'=>'4','position_id'=>'8','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José de Jesus dos Santos','gender'=>'M','municipal_id'=>'5','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Noronha','gender'=>'M','municipal_id'=>'5','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Atibo Tilman','gender'=>'M','municipal_id'=>'5','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zelia F da Conceição (posisaun troka ona)','gender'=>'F','municipal_id'=>'5','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Cristalina Moniz','gender'=>'F','municipal_id'=>'5','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Adelina Encarnação','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agustinha de Araujo','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Apolonio Amaral','gender'=>'M','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernanda Moniz Amaral','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natercia Xinanes Barros','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Nazaria de Jesus','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Nazaria dos Reis Pereira da Silva','gender'=>'F','municipal_id'=>'5','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aguinelio Antonio Sarmento do Rego','gender'=>'M','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Bernadete de Jesus Inacia','gender'=>'F','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Daniel dos Reis','gender'=>'M','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Isabel de Araujo','gender'=>'F','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jean Paulo Cruz da Costa','gender'=>'M','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mario Barreto','gender'=>'M','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ruben do Rego Afonso','gender'=>'M','municipal_id'=>'5','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alberto dos Reis','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlito Barros dos Reis','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Denciana Pereira Gonçalves','gender'=>'F','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Guterres','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio de Jesus Maia','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Pedro de Araujo Gomes','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rui Lopes','gender'=>'M','municipal_id'=>'5','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Sabino Amaral','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Tadeo Francisco de Araújo Soares','gender'=>'M','municipal_id'=>'6','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ivonia Pereira Amaral','gender'=>'F','municipal_id'=>'6','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jacinta Manuela Freitas','gender'=>'F','municipal_id'=>'6','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Flavio Maria Graça Amaral','gender'=>'M','municipal_id'=>'6','position_id'=>'9','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Prodenciano Maria Soares','gender'=>'M','municipal_id'=>'6','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos Soares Airai','gender'=>'M','municipal_id'=>'6','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alice Jeronimo Guterres','gender'=>'F','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eldina da Silva','gender'=>'F','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Flavia Moniz Afonso Barreto','gender'=>'F','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jocas Marques','gender'=>'M','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Isabel da Costa Guterres','gender'=>'F','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosa Bonaparte Soares','gender'=>'F','municipal_id'=>'6','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aniceto Magno de Araujo','gender'=>'M','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carol Martins dos Reis Barreto','gender'=>'F','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gilberto Amaral','gender'=>'M','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joaquim Godinho','gender'=>'M','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Leopoldo Moniz dos Santos Maia','gender'=>'M','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Angelina Ricardo Marçal','gender'=>'F','municipal_id'=>'6','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Andre Pinto','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio Maria Sarmento de Carvalho','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisca Antonia de Fatima Oliveir','gender'=>'F','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Geraldo Manuel da Costa','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Herlina da Silva Cardoso','gender'=>'F','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ilidio Soares','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Oliveira Mota','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Laurindo Dias','gender'=>'M','municipal_id'=>'6','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mariana Maia da Cruz','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joao Bosco Soares','gender'=>'M','municipal_id'=>'7','position_id'=>'1','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Jacinta Soares de Deus','gender'=>'F','municipal_id'=>'7','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natalia Fatima de Jesus','gender'=>'F','municipal_id'=>'7','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Afonso Fernandes Ximenes','gender'=>'M','municipal_id'=>'7','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Martinho de Deus','gender'=>'M','municipal_id'=>'7','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jaime Soares dos Santos','gender'=>'M','municipal_id'=>'7','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Angela Exposto','gender'=>'F','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aniceto Carvalho Martins','gender'=>'M','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Canario Florindo das Neves','gender'=>'M','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Clarina Gomes Martins','gender'=>'F','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Emercio Arauju Barros','gender'=>'M','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eva Barros Martins','gender'=>'F','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joaninha do Rego Mesquita','gender'=>'F','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio Soares Pereira','gender'=>'M','municipal_id'=>'7','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elias de Carvalho Madeira','gender'=>'M','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jaimito das Neves Salsinha','gender'=>'M','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natalina Soares Marques','gender'=>'F','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Noe de Jesus Oliveira','gender'=>'M','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Noelia Soares','gender'=>'F','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Odete Barros Lemos','gender'=>'F','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Pedro Mendonça','gender'=>'M','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zenaida Amelia Soares','gender'=>'F','municipal_id'=>'7','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Abilio Araujo','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Evaristo Martins dos Reis','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisca Agata Sriati Silva Soares','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisco Carlota','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ismael Gonçalves','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julia de Deus Gomes','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Luciana Martins','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Luciano Jose Antonio Maia','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lucinda Menezes Babo','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Soares Lequi','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marcia dos Santos Exposto','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Soares de Jesus','gender'=>'F','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Sebastiao Abel de Deus','gender'=>'M','municipal_id'=>'7','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Delfim de Jesus','gender'=>'M','municipal_id'=>'7','position_id'=>'1','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Acasio Carvalho','gender'=>'M','municipal_id'=>'8','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Wilson Jose Caetano da Costa','gender'=>'M','municipal_id'=>'8','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Herculano Correia','gender'=>'M','municipal_id'=>'8','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ildefonso Nunes','gender'=>'M','municipal_id'=>'8','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Domingos de Jesus','gender'=>'M','municipal_id'=>'8','position_id'=>'4','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Adelina Dias Soares','gender'=>'F','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agueda de Jesus Almeida','gender'=>'F','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ana da Silva','gender'=>'F','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Arcancio da Conceição','gender'=>'M','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Belina dos Santos','gender'=>'F','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Cristianti de Jesus Rodrigues','gender'=>'M','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio Lobo','gender'=>'M','municipal_id'=>'8','position_id'=>'5','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Alcino da Silva','gender'=>'M','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Bernardo Almeida','gender'=>'M','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Eugenio Correia Guterres','gender'=>'M','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gaspar de Rosa Pereira','gender'=>'M','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Petronila Escorial dos Santos','gender'=>'F','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Raimundo Noronha','gender'=>'M','municipal_id'=>'8','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Adriano de Carvalho','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Andrade Carvalho','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Armindo da Costa Guimarães','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Boaventura Sejaltino Viana Bite','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Celestino dos Santos Eloy','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elio Pereira','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ercilia de Jesus','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Ernesto de Jesus Faria','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Hendro Agustinho Machado','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joanita Guimarães','gender'=>'F','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Soriano Soares','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Neftalin Mariano Patrício Barreto d','gender'=>'M','municipal_id'=>'8','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernando Gonçalves','gender'=>'M','municipal_id'=>'8','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aderita Lopes da Silva Pires','gender'=>'F','municipal_id'=>'9','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Ria Sidonia de Jesus Nunes Pereira','gender'=>'F','municipal_id'=>'9','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Anselmus Oktavianus de Jesus Bere','gender'=>'M','municipal_id'=>'9','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Awal Verdial','gender'=>'M','municipal_id'=>'9','position_id'=>'9','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julito da Cruz Pui','gender'=>'M','municipal_id'=>'9','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fatima Maria Afonso','gender'=>'F','municipal_id'=>'9','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Olga da Costa Vidigal','gender'=>'F','municipal_id'=>'9','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alcino Freitas Lopes da Cruz','gender'=>'M','municipal_id'=>'9','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Isabel dos Santos','gender'=>'F','municipal_id'=>'9','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria de Fatima Correia','gender'=>'F','municipal_id'=>'9','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Arnaldo dos Santos Gonçalves','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eldino Rodrigues dos Santos','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Gil dos Santos','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Afonso','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Soares','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Nazario Xavier','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Saturnino da Costa','gender'=>'M','municipal_id'=>'9','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lucio Júlio Guterres','gender'=>'M','municipal_id'=>'9','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio Barros de Araujo','gender'=>'M','municipal_id'=>'10','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marito Pinto','gender'=>'M','municipal_id'=>'10','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Sabino Bernadino da Conceicao Salda','gender'=>'M','municipal_id'=>'10','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Vladimir Sertorio de Sa Benevides','gender'=>'M','municipal_id'=>'10','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosito Marcelo Gusmão','gender'=>'M','municipal_id'=>'10','position_id'=>'10','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Artur Venancio Soares','gender'=>'M','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisca de Almeida','gender'=>'F','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lizia do Rosario de Fatima Soares','gender'=>'F','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marcelina Carceres Paulo','gender'=>'F','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosalia de Jesus Gusmão Vas','gender'=>'F','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Tomasia Gusmão','gender'=>'F','municipal_id'=>'10','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio de Jesus','gender'=>'M','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Diamantina Correia','gender'=>'F','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elias João Soares','gender'=>'M','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernanda de Sousa Gusmão','gender'=>'F','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Carceres Correia','gender'=>'M','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Moises Anibal da Cruz','gender'=>'M','municipal_id'=>'10','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Domingas Gilpia da Costa Soares','gender'=>'F','municipal_id'=>'10','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Edfra Maria Gomes Sarmento','gender'=>'F','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elsa da Conceição Lopes Pires','gender'=>'F','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Filipe de Oliveira','gender'=>'M','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joao Gusmao  Costa Viegas','gender'=>'M','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julito da Cunha','gender'=>'M','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosalino de Nola Soares','gender'=>'M','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Terezinha da Costa Moniz','gender'=>'F','municipal_id'=>'10','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Sidonio Gusmao','gender'=>'M','municipal_id'=>'10','position_id'=>'1','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Apolonia Lucia Lulu de Araujo','gender'=>'F','municipal_id'=>'10','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Madalena Maria de Fatima Soares','gender'=>'F','municipal_id'=>'11','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eldito da Costa Mendes','gender'=>'M','municipal_id'=>'11','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Luis Marçal da CostaTavares','gender'=>'M','municipal_id'=>'11','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natalino de Andrade','gender'=>'M','municipal_id'=>'11','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Abril dos Reis','gender'=>'M','municipal_id'=>'11','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Atanasio Ramos Gusmão','gender'=>'M','municipal_id'=>'11','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Dulce Fernandes Ximenes','gender'=>'F','municipal_id'=>'11','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Isabel da Costa','gender'=>'F','municipal_id'=>'11','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Norberto Ornai','gender'=>'M','municipal_id'=>'11','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Januario Rodrigues','gender'=>'M','municipal_id'=>'11','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Leonia Pinto Correia','gender'=>'F','municipal_id'=>'11','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Pereira','gender'=>'M','municipal_id'=>'11','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marcos Monteiro','gender'=>'M','municipal_id'=>'11','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Santina da Costa Barros','gender'=>'F','municipal_id'=>'11','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Carlos dos Reis','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Estevão Alves Xavier','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Inacio de Jesus Gomes','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jacinta da Costa Louverny','gender'=>'F','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Jaime da Costa Xavier','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lucio Barreto','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Onofre da Silva','gender'=>'M','municipal_id'=>'11','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Sebastiao Tanesi','gender'=>'M','municipal_id'=>'11','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agustinho Taec','gender'=>'M','municipal_id'=>'11','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joao Bobo','gender'=>'M','municipal_id'=>'11','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisco Caet','gender'=>'M','municipal_id'=>'12','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Remigio Nuno Sila','gender'=>'M','municipal_id'=>'12','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Baptista Colo','gender'=>'M','municipal_id'=>'12','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fatima Obe','gender'=>'F','municipal_id'=>'12','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria de Fatima Sila','gender'=>'F','municipal_id'=>'12','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Sequeira Eli','gender'=>'F','municipal_id'=>'12','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natalia Maria da Costa Marques Conc','gender'=>'F','municipal_id'=>'12','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Albino Romeia da Crus Salu','gender'=>'M','municipal_id'=>'12','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Octavio Nicolau Maia','gender'=>'M','municipal_id'=>'12','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Serafin Soares Lafo','gender'=>'M','municipal_id'=>'12','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Umberto Nino','gender'=>'M','municipal_id'=>'12','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alsinu Bas Fallo','gender'=>'M','municipal_id'=>'12','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio Sequeira Beno Falo','gender'=>'M','municipal_id'=>'12','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Edita Afoan','gender'=>'F','municipal_id'=>'12','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisca Marques','gender'=>'F','municipal_id'=>'12','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Thomas Americo Boquifai','gender'=>'M','municipal_id'=>'12','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Estevão de Carvalho','gender'=>'M','municipal_id'=>'12','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agustinho Guterres','gender'=>'M','municipal_id'=>'12','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julmira Fernandes Pinto','gender'=>'F','municipal_id'=>'13','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'José Manuel','gender'=>'M','municipal_id'=>'13','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Monis dos Reis Fernandes','gender'=>'M','municipal_id'=>'13','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Alcino Fernandes','gender'=>'M','municipal_id'=>'13','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Eva de Fatima','gender'=>'F','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fernanda Alves','gender'=>'F','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Hermenegildo de Jesus Menezes','gender'=>'M','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Julio da Costa Oliveira','gender'=>'M','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Juvinal Soares de Ressurição','gender'=>'M','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Agustinho Pinto','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Agustinho Pinto','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Domingos Marçal da Silva Amaral','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Elda Marques','gender'=>'F','municipal_id'=>'13','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Higinio Posinato Zamor e Silva','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Luzinho Martins','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Manuel Soares da Costa','gender'=>'M','municipal_id'=>'13','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio da Silva','gender'=>'M','municipal_id'=>'13','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Bendita Freitas Soares','gender'=>'F','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Clementino do Rosario','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Domingos da Costa','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisco Soares Varela','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'João Belo Marques','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mario da Silva','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Natalino da Costa de Jesus','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Nazario Amaral','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Romeu Santozinho Neves de Carvalho','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosito Soares Guterres','gender'=>'M','municipal_id'=>'13','position_id'=>'7','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Joens Pinto','gender'=>'M','municipal_id'=>'13','position_id'=>'12','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Paula Fernandes dos Santos','gender'=>'F','municipal_id'=>'13','position_id'=>'2','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Francisco Seac','gender'=>'M','municipal_id'=>'13','position_id'=>'12','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Maria Gusmao','gender'=>'F','municipal_id'=>'13','position_id'=>'11','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marito Alves','gender'=>'M','municipal_id'=>'13','position_id'=>'9','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Lilia Lay','gender'=>'F','municipal_id'=>'14','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Marcio Marcal','gender'=>'M','municipal_id'=>'14','position_id'=>'13','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rogerio Muakandala','gender'=>'M','municipal_id'=>'14','position_id'=>'8','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Bartolomeu Diaz Tilman','gender'=>'M','municipal_id'=>'14','position_id'=>'8','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Moises Salsinha','gender'=>'M','municipal_id'=>'14','position_id'=>'6','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fortunato Amaral','gender'=>'M','municipal_id'=>'14','position_id'=>'11','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Rosito Guterres','gender'=>'M','municipal_id'=>'14','position_id'=>'13','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Dulce Guterres Junio','gender'=>'F','municipal_id'=>'14','position_id'=>'14','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Olderico Lopes','gender'=>'M','municipal_id'=>'14','position_id'=>'11','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Joao Moreira','gender'=>'M','municipal_id'=>'14','position_id'=>'11','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Secondino Moreira','gender'=>'M','municipal_id'=>'14','position_id'=>'16','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Zelia Freitas da Conceição','gender'=>'F','municipal_id'=>'14','position_id'=>'1','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Castro Gusmao','gender'=>'M','municipal_id'=>'14','position_id'=>'5','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Tezar Aini','gender'=>'M','municipal_id'=>'14','position_id'=>'4','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Mario da Silva','gender'=>'M','municipal_id'=>'14','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Antonio da Silva','gender'=>'M','municipal_id'=>'14','position_id'=>'3','institution_id'=>'1','status'=>'0']);
        Counterpart::create(['name'=>'Celsio Julio Babo','gender'=>'M','municipal_id'=>'14','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Fidel','gender'=>'M','municipal_id'=>'14','position_id'=>'3','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Aderito Soares dos Reis','gender'=>'M','municipal_id'=>'14','position_id'=>'9','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Edy Tome Nunes','gender'=>'M','municipal_id'=>'14','position_id'=>'9','institution_id'=>'1','status'=>'1']);
        Counterpart::create(['name'=>'Adriano da Cruz','gender'=>'M','municipal_id'=>'4','position_id'=>'17','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Adriano Bere','gender'=>'M','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Domingas T. dos Santos   ','gender'=>'F','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Berta Tavares','gender'=>'F','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Crispin Moniz','gender'=>'M','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Jacinta de Jesus Araujo','gender'=>'F','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Raqela Godinho','gender'=>'F','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Armindo Cardoso Barros','gender'=>'M','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Maria de Fatima','gender'=>'F','municipal_id'=>'4','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Agusto Moniz do Santos','gender'=>'M','municipal_id'=>'4','position_id'=>'19','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Pedro Alexandre Guterres Pereira','gender'=>'M','municipal_id'=>'3','position_id'=>'17','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Adelina Pinto da Costa','gender'=>'F','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Edviges Xavier Freitas','gender'=>'F','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Francisco da Silva','gender'=>'M','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Jose Ricardo de J. Freitas','gender'=>'M','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Justina Mariz','gender'=>'F','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Maria Imaculada Soares','gender'=>'F','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Norberta da Costa','gender'=>'F','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
        Counterpart::create(['name'=>'Zeferino Menezes','gender'=>'M','municipal_id'=>'3','position_id'=>'18','institution_id'=>'2','status'=>'1']);
                
    }
}
